/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.ResultSetMetaData; 
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List; 
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
public class NewJFrame extends javax.swing.JFrame {
    
    private NewJFrame1 njf1;
    private NewJFrame2 njf2;
    private updateJFrame ujf;
    
    public NewJFrame() {
        initComponents();
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs; 
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/normalization", "root", "Paologab@030802");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SexGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Admission_Number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Birthday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        M = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Email_Address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Religion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Nationality = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Postal_Code = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Program = new javax.swing.JTextField();
        Birthplace = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Permanent_Address = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Contact_Number = new javax.swing.JTextField();
        Add_prev_school_btn = new javax.swing.JButton();
        Add_guardian_btn = new javax.swing.JButton();
        save_all_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Campus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Admission Number: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        Admission_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admission_NumberActionPerformed(evt);
            }
        });
        jPanel2.add(Admission_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Birthday [YYYY-MM-DD]: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));
        jPanel2.add(Birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 270, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sex: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        SexGroup.add(M);
        M.setText("M");
        jPanel2.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        SexGroup.add(F);
        F.setText("F");
        jPanel2.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("City: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));
        jPanel2.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Email Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));
        jPanel2.add(Email_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Campus: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Religion: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));
        jPanel2.add(Religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 181, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nationality:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));
        jPanel2.add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 181, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Postal Code: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));
        jPanel2.add(Postal_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 181, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Place of Birth: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Program:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, -1));
        jPanel2.add(Program, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 181, -1));

        Birthplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthplaceActionPerformed(evt);
            }
        });
        jPanel2.add(Birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 181, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Permanent Address:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        Permanent_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Permanent_AddressActionPerformed(evt);
            }
        });
        jPanel2.add(Permanent_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 181, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Contact Number:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        Contact_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact_NumberActionPerformed(evt);
            }
        });
        jPanel2.add(Contact_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 205, -1));

        Add_prev_school_btn.setText("Add Previous School ");
        Add_prev_school_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_prev_school_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Add_prev_school_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        Add_guardian_btn.setText("Add Guardian");
        Add_guardian_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_guardian_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Add_guardian_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        save_all_btn.setText("SAVE ALL");
        save_all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_all_btnActionPerformed(evt);
            }
        });
        jPanel2.add(save_all_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        reset_btn.setText("RESET");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel2.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        exit_btn.setText("EXIT");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, -1, -1));

        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel2.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Student Name [LN, FN, MI]: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 100, -1));

        Campus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main", "Biringan", "Sun and Moon" }));
        Campus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampusActionPerformed(evt);
            }
        });
        jPanel2.add(Campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Student Info.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_prev_school_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_prev_school_btnActionPerformed
        // TODO add your handling code here:
        njf1 = new NewJFrame1(con, Admission_Number.getText()); 
        njf1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Set the close operation to hide the frame
        njf1.setVisible(true); // Display previous school input details
        
    }//GEN-LAST:event_Add_prev_school_btnActionPerformed

    private void Add_guardian_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_guardian_btnActionPerformed
        // TODO add your handling code here:
        njf2 = new NewJFrame2(con, Admission_Number.getText()); 
        njf2.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Set the close operation to hide the frame
        njf2.setVisible(true); // Display guardian input details
        
    }//GEN-LAST:event_Add_guardian_btnActionPerformed

    private void BirthplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthplaceActionPerformed

    private void Permanent_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Permanent_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Permanent_AddressActionPerformed

    private void Contact_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contact_NumberActionPerformed

    private void save_all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_all_btnActionPerformed

        try {
            String admissionNumber = Admission_Number.getText();
            String studentName = Name.getText();
            String birthday = Birthday.getText();
            String sex;
            if (M.isSelected()) {
                sex = "M";
            } else if (F.isSelected()) {
                sex = "F";
            } else {
                // Handle the case when no radio button is selected
                sex = ""; // or you can assign a default value
            }
            String city = City.getText();
            String emailAddress = Email_Address.getText();
            String campus = (String) Campus.getSelectedItem();
            String religion = Religion.getText();
            String nationality = Nationality.getText();
            String postalCode = Postal_Code.getText();
            String program = Program.getText();
            String birthplace = Birthplace.getText();
            String permanentAddress = Permanent_Address.getText();
            String contactNumber = Contact_Number.getText();
             
            pst = con.prepareStatement("INSERT INTO student_info(Admission_Number, Name, Birthday, Sex, City, Email_Address, Campus, Religion, Nationality, Postal_Code, Program, Birthplace, Permanent_Address, Contact_Number) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, admissionNumber);
            pst.setString(2, studentName);
            pst.setString(3, birthday);
            pst.setString(4, sex);
            pst.setString(5, city);
            pst.setString(6, emailAddress);
            pst.setString(7, campus);
            pst.setString(8, religion);
            pst.setString(9, nationality);
            pst.setString(10, postalCode);
            pst.setString(11, program);
            pst.setString(12, birthplace);
            pst.setString(13, permanentAddress);
            pst.setString(14, contactNumber);
            
            int studentRowsAffected = pst.executeUpdate();          
            
                    
            ArrayList<String> schoolIds = njf1.getSchoolIds();
            ArrayList<String> startDates = njf1.getStartDates();
            ArrayList<String> endDates = njf1.getEndDates();
            ArrayList<String> namesOfPreviousSchool = njf1.getNamesOfPreviousSchool();
            ArrayList<String> classStandings = njf1.getClassStandings();
            ArrayList<String> schoolAddresses = njf1.getSchoolAddresses();
            
            pst = con.prepareStatement("INSERT INTO school_info(School_Id, Start_Date, End_Date, Name_of_previous_school, Class_standing, School_address, Admission_Number) VALUES(?,?,?,?,?,?,?)");
            int schoolRowsAffected = 0;
            for (int i = 0; i < schoolIds.size(); i++) {
                pst.setString(1, schoolIds.get(i));
                pst.setString(2, startDates.get(i));
                pst.setString(3, endDates.get(i));
                pst.setString(4, namesOfPreviousSchool.get(i));
                pst.setString(5, classStandings.get(i));
                pst.setString(6, schoolAddresses.get(i));
                pst.setString(7, admissionNumber);
                
                schoolRowsAffected += pst.executeUpdate(); 
            }
            
            
            ArrayList<String> philsysIds = njf2.getPhilsysIds();
            ArrayList<String> guardianNames = njf2.getGuardianNames();
            ArrayList<String> relationships = njf2.getRelationships();
            ArrayList<String> occupations = njf2.getOccupations();
            ArrayList<String> gAddresses= njf2.getGAddresses();
            ArrayList<String> gPostalCodes = njf2.getGPostalCodes();
            ArrayList<String> gCitys = njf2.getGCitys();
            ArrayList<String> gContactNumbers = njf2.getGContactNumbers();
            ArrayList<String> gEmailAddresses = njf2.getGEmailAddresses();
            
            pst = con.prepareStatement("INSERT INTO guardian_info(Philsys_Id, Guardian_Name, Relationship, Occupation, G_Address, G_Postal_Code, G_City, G_Contact_Number, G_Email_Address, Admission_Number) VALUES(?,?,?,?,?,?,?,?,?,?)");
            int guardianRowsAffected = 0;
            for (int j = 0; j < philsysIds.size(); j++) {
                pst.setString(1, philsysIds.get(j));
                pst.setString(2, guardianNames.get(j));
                pst.setString(3, relationships.get(j));
                pst.setString(4, occupations.get(j));
                pst.setString(5, gAddresses.get(j));
                pst.setString(6, gPostalCodes.get(j));
                pst.setString(7, gCitys.get(j));
                pst.setString(8, gContactNumbers.get(j));
                pst.setString(9, gEmailAddresses.get(j));
                pst.setString(10, admissionNumber);
                
                guardianRowsAffected += pst.executeUpdate();
            }
            
            
            if (studentRowsAffected == 1 && schoolIds.size() == schoolRowsAffected && philsysIds.size() == guardianRowsAffected) {
                JOptionPane.showMessageDialog(this, "Record Added");
                Admission_Number.setText("");
                Name.setText("");
                Birthday.setText("");
                SexGroup.clearSelection();
                City.setText("");
                Email_Address.setText("");
                Campus.setSelectedIndex(0);
                Religion.setText("");
                Nationality.setText("");
                Postal_Code.setText("");
                Program.setText("");
                Birthplace.setText("");
                Permanent_Address.setText("");
                Contact_Number.setText("");
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Record Failed");
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_save_all_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ujf = new updateJFrame(); 
        ujf.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); 
        ujf.setVisible(true);
    }//GEN-LAST:event_update_btnActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
    Admission_Number.setText("");
    Name.setText("");
    Birthday.setText("");
    SexGroup.clearSelection();
    City.setText("");
    Email_Address.setText("");
    Campus.setSelectedIndex(0);
    Religion.setText("");
    Nationality.setText("");
    Postal_Code.setText("");
    Program.setText("");
    Birthplace.setText("");
    Permanent_Address.setText("");
    Contact_Number.setText("");
    }//GEN-LAST:event_reset_btnActionPerformed
private JFrame frame;
    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "MySql Connector", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exit_btnActionPerformed

    private void Admission_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admission_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admission_NumberActionPerformed

    private void CampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampusActionPerformed
        // TODO add your handling code here:
        String selectedValue = Campus.getSelectedItem().toString();
    }//GEN-LAST:event_CampusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_guardian_btn;
    private javax.swing.JButton Add_prev_school_btn;
    private javax.swing.JTextField Admission_Number;
    private javax.swing.JTextField Birthday;
    private javax.swing.JTextField Birthplace;
    private javax.swing.JComboBox<String> Campus;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Contact_Number;
    private javax.swing.JTextField Email_Address;
    private javax.swing.JRadioButton F;
    private javax.swing.JRadioButton M;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Nationality;
    private javax.swing.JTextField Permanent_Address;
    private javax.swing.JTextField Postal_Code;
    private javax.swing.JTextField Program;
    private javax.swing.JTextField Religion;
    private javax.swing.ButtonGroup SexGroup;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_all_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
