/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.ResultSetMetaData; 
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List; 
import java.util.ArrayList;
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    private Connection con; 
    private String admissionNumber;
    private ArrayList<String> schoolIds;
    private ArrayList<String> startDates;
    private ArrayList<String> endDates;
    private ArrayList<String> namesOfPreviousSchool;
    private ArrayList<String> classStandings;
    private ArrayList<String> schoolAddresses;
    private updateJFrame ujf;
    
    
    public NewJFrame1(Connection con, String admissionNumber) {
        this.con = con;
        this.admissionNumber = admissionNumber;
        schoolIds = new ArrayList<>();
        startDates = new ArrayList<>();
        endDates = new ArrayList<>();
        namesOfPreviousSchool = new ArrayList<>();
        classStandings = new ArrayList<>();
        schoolAddresses = new ArrayList<>();
        initComponents();
    }
    
    
    public String getSchoolId() {
        return School_id.getText();
    }

    public String getstartDate() {
        return Start_Date.getText();
    }

    public String getendDate() {
        return End_Date.getText();
    }

    public String getNameOfPreviousSchool() {
        return Name_of_previous_school.getText();
    }

    public String getClassStanding() {
        return Class_standing.getText();
    }

    public String getSchoolAddress() {
        return School_address.getText();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        School_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Start_Date = new javax.swing.JTextField();
        End_Date = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Class_standing = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        School_address = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Name_of_previous_school = new javax.swing.JTextField();
        save_prev_school_btn = new javax.swing.JButton();
        close_prev_school_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        School_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_idActionPerformed(evt);
            }
        });
        jPanel1.add(School_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 214, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Start:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("End:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("School ID:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));
        jPanel1.add(Start_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 181, -1));

        End_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                End_DateActionPerformed(evt);
            }
        });
        jPanel1.add(End_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 181, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Name of Previous School: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        Class_standing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_standingActionPerformed(evt);
            }
        });
        jPanel1.add(Class_standing, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 181, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("School Address: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        School_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_addressActionPerformed(evt);
            }
        });
        jPanel1.add(School_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 205, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Class Standing: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        Name_of_previous_school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_of_previous_schoolActionPerformed(evt);
            }
        });
        jPanel1.add(Name_of_previous_school, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 214, -1));

        save_prev_school_btn.setText("SAVE");
        save_prev_school_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_prev_school_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_prev_school_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        close_prev_school_btn.setText("CLOSE");
        close_prev_school_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_prev_school_btnActionPerformed(evt);
            }
        });
        jPanel1.add(close_prev_school_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prev school info.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void School_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_School_idActionPerformed

    private void End_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_End_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_End_DateActionPerformed

    private void Class_standingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_standingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class_standingActionPerformed

    private void School_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_School_addressActionPerformed

    private void Name_of_previous_schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_of_previous_schoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_of_previous_schoolActionPerformed

    private void close_prev_school_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_prev_school_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_prev_school_btnActionPerformed

    private void save_prev_school_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_prev_school_btnActionPerformed
        // TODO add your handling code here:
        try {
            String schoolId = School_id.getText();
            String startDate = Start_Date.getText();
            String endDate = End_Date.getText();
            String nameOfPreviousSchool = Name_of_previous_school.getText();
            String classStanding = Class_standing.getText();
            String schoolAddress = School_address.getText();

            schoolIds.add(schoolId);
            startDates.add(startDate);
            endDates.add(endDate);
            namesOfPreviousSchool.add(nameOfPreviousSchool);
            classStandings.add(classStanding);
            schoolAddresses.add(schoolAddress);

            School_id.setText("");
            Start_Date.setText("");
            End_Date.setText("");
            Name_of_previous_school.setText("");
            Class_standing.setText("");
            School_address.setText("");

            JOptionPane.showMessageDialog(this, "School Information Added");
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_save_prev_school_btnActionPerformed
    public ArrayList<String> getSchoolIds() {
        return schoolIds;
    }

    public ArrayList<String> getStartDates() {
        return startDates;
    }

    public ArrayList<String> getEndDates() {
        return endDates;
    }

    public ArrayList<String> getNamesOfPreviousSchool() {
        return namesOfPreviousSchool;
    }

    public ArrayList<String> getClassStandings() {
        return classStandings;
    }

    public ArrayList<String> getSchoolAddresses() {
        return schoolAddresses;
    }
    // Helper method to clear the input fields
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Class_standing;
    private javax.swing.JTextField End_Date;
    private javax.swing.JTextField Name_of_previous_school;
    private javax.swing.JTextField School_address;
    private javax.swing.JTextField School_id;
    private javax.swing.JTextField Start_Date;
    private javax.swing.JButton close_prev_school_btn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save_prev_school_btn;
    // End of variables declaration//GEN-END:variables
    
    
}
