/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.ResultSetMetaData; 
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.List;
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    private Connection con; 
    private String admissionNumber;
    private ArrayList<String> philsysIds;
    private ArrayList<String> guardianNames;
    private ArrayList<String> relationships;
    private ArrayList<String> occupations;
    private ArrayList<String> gAddresses;
    private ArrayList<String> gPostalCodes;
    private ArrayList<String> gCitys;
    private ArrayList<String> gContactNumbers;
    private ArrayList<String> gEmailAddresses;
    
    public NewJFrame2(Connection con, String admissionNumber) {
        this.con = con;
        this.admissionNumber = admissionNumber;
        philsysIds = new ArrayList<>();
        guardianNames = new ArrayList<>();
        relationships = new ArrayList<>();
        occupations = new ArrayList<>();
        gAddresses = new ArrayList<>();
        gPostalCodes = new ArrayList<>();
        gCitys = new ArrayList<>();
        gContactNumbers = new ArrayList<>();
        gEmailAddresses = new ArrayList<>();
        initComponents();
    }
    
    public String getPhilsysId() {
        return Philsys_id.getText();
    }
    
    public String getGuardianName() {
        return Guardian_Name.getText();
    }

    public String getRelationship() {
        return Relationship.getText();
    }

    public String getOccupation() {
        return Occupation.getText();
    }

    public String getGuardianAddress() {
        return G_adress.getText();
    }
    
    public String getGuardianCity() {
        return G_city.getText();
    }
    
    public String getGuardianPostalCode() {
        return G_Postal_code.getText();
    }
    
    public String getGuardianContactNumber() {
        return G_Contact_Number.getText();
    }
    
    public String getGuardianEmailAddress() {
        return G_Email_address.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Philsys_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Guardian_Name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Occupation = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Relationship = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        G_adress = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        G_city = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        G_Postal_code = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        G_Contact_Number = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        G_Email_address = new javax.swing.JTextField();
        save_guardian_btn = new javax.swing.JButton();
        close_guardian_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("PhilSys ID: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        Philsys_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Philsys_idActionPerformed(evt);
            }
        });
        jPanel1.add(Philsys_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 214, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Name of Guardian: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Guardian_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardian_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Guardian_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 214, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Relationship: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        Occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccupationActionPerformed(evt);
            }
        });
        jPanel1.add(Occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 214, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Occupation: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        Relationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationshipActionPerformed(evt);
            }
        });
        jPanel1.add(Relationship, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 214, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Address:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        G_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_adressActionPerformed(evt);
            }
        });
        jPanel1.add(G_adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 214, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("City: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        G_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_cityActionPerformed(evt);
            }
        });
        jPanel1.add(G_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 214, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Postal Code: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        G_Postal_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_Postal_codeActionPerformed(evt);
            }
        });
        jPanel1.add(G_Postal_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 214, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Contact Number: ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        G_Contact_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_Contact_NumberActionPerformed(evt);
            }
        });
        jPanel1.add(G_Contact_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 214, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Email Address: ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        G_Email_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_Email_addressActionPerformed(evt);
            }
        });
        jPanel1.add(G_Email_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 214, -1));

        save_guardian_btn.setText("SAVE ");
        save_guardian_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_guardian_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_guardian_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        close_guardian_btn.setText("CLOSE");
        close_guardian_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_guardian_btnActionPerformed(evt);
            }
        });
        jPanel1.add(close_guardian_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guardian info.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Philsys_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Philsys_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Philsys_idActionPerformed

    private void Guardian_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardian_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Guardian_NameActionPerformed

    private void OccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OccupationActionPerformed

    private void RelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelationshipActionPerformed

    private void G_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_adressActionPerformed

    private void G_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_cityActionPerformed

    private void G_Postal_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_Postal_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_Postal_codeActionPerformed

    private void G_Contact_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_Contact_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_Contact_NumberActionPerformed

    private void G_Email_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_Email_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_Email_addressActionPerformed

    private void save_guardian_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_guardian_btnActionPerformed
        // TODO add your handling code here:
        try{
            String philsysId = Philsys_id.getText();
            String guardianName= Guardian_Name.getText();
            String relationship= Relationship.getText();
            String occupation = Occupation.getText();
            String gAddress = G_adress.getText();
            String gCity = G_city.getText();
            String gPostalCode = G_Postal_code.getText();
            String gContactNumber = G_Contact_Number.getText();
            String gEmailAddress = G_Email_address.getText();

            philsysIds.add(philsysId);
            guardianNames.add(guardianName);
            relationships.add(relationship);
            occupations.add(occupation);
            gAddresses.add(gAddress);
            gCitys.add(gCity);
            gPostalCodes.add(gPostalCode);
            gContactNumbers.add(gContactNumber);
            gEmailAddresses.add(gEmailAddress);

            Philsys_id.setText("");
            Guardian_Name.setText("");
            Relationship.setText("");
            Occupation.setText("");
            G_adress.setText("");
            G_city.setText("");
            G_Postal_code.setText("");
            G_Contact_Number.setText("");
            G_Email_address.setText("");
          
            JOptionPane.showMessageDialog(this, "Guardian Information Added");
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_guardian_btnActionPerformed
    public ArrayList<String> getPhilsysIds() {
        return philsysIds;
    }

    public ArrayList<String> getGuardianNames() {
        return guardianNames;
    }

    public ArrayList<String> getRelationships() {
        return relationships;
    }

    public ArrayList<String> getOccupations() {
        return occupations;
    }

    public ArrayList<String> getGAddresses() {
        return gAddresses;
    }

    public ArrayList<String> getGPostalCodes() {
        return gPostalCodes;
    }
    
    public ArrayList<String> getGCitys() {
        return gCitys;
    }
    
    public ArrayList<String> getGContactNumbers() {
        return gContactNumbers;
    }
    
    public ArrayList<String> getGEmailAddresses() {
        return gEmailAddresses;
    }
    private void close_guardian_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_guardian_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_guardian_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField G_Contact_Number;
    private javax.swing.JTextField G_Email_address;
    private javax.swing.JTextField G_Postal_code;
    private javax.swing.JTextField G_adress;
    private javax.swing.JTextField G_city;
    private javax.swing.JTextField Guardian_Name;
    private javax.swing.JTextField Occupation;
    private javax.swing.JTextField Philsys_id;
    private javax.swing.JTextField Relationship;
    private javax.swing.JButton close_guardian_btn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save_guardian_btn;
    // End of variables declaration//GEN-END:variables
}
